### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by tiliarou** [tanaikech/ggsrun#1]
I get an error:
`panic: runtime error: index out of range [0] with length 0`

when trying to run ggsrun auth

Windows 10 1909 x64, under powershell via windows terminal.
I don't really understand the error...

`goroutine 1 [running]:
main.(*AuthContainer).getNewAccesstoken(0xc00002ccc0, 0xc00002ccc0)
        D:/build/ggsrun/oauth.go:235 +0x1124
main.(*AuthContainer).reAuth(0xc00002ccc0)
        D:/build/ggsrun/oauth.go:55 +0x40
main.reAuth(0xc00002cc80, 0x2, 0x2)
        D:/build/ggsrun/handler.go:142 +0x5c
github.com/urfave/cli.(*Command).Run(0xc000113680, 0xc00002cb40, 0x0, 0x0)
        C:/Go/projects/src/github.com/urfave/cli/command.go:161 +0x4e7
github.com/urfave/cli.(*App).RunContext(0xc000043200, 0x972340, 0xc0000200b0, 0xc000004480, 0x2, 0x2, 0x0, 0x0)
        C:/Go/projects/src/github.com/urfave/cli/app.go:301 +0x81b
github.com/urfave/cli.(*App).Run(...)
        C:/Go/projects/src/github.com/urfave/cli/app.go:210
main.main()
        D:/build/ggsrun/ggsrun.go:565 +0x4dd5`

**Comment by tiliarou** [comment]
My bad: I used a webapp credential in the json, whereas it should have been a desktop app.
It works now.
